doctrine:
    dbal:
        default_connection: betInstinct
        connections:
            betInstinct:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            betResultat:
                url: '%env(resolve:DATABASE_RESULTAT_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: betInstinct
        entity_managers:
                betInstinct:
                    connection: betInstinct
                    mappings:
                        betInstinct:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Entity/BetInstinct'
                            prefix: 'App\Entity\BetInstinct'
                            alias: BetInstinct
                betResultat:
                    connection: betResultat
                    mappings:
                        betResultat:
                             is_bundle: false
                             type: annotation
                             dir: '%kernel.project_dir%/src/Entity/BetResultat'
                             prefix: 'App\Entity\BetResultat'
                             alias: BetResultat
